/*
 * Fitness App
 *
 * This is a CRUD API for fitness app.
 *
 * API version: 1.0.0
 * Contact: soarex16@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package domain

type Achievement struct {
	Id string `json:"id,omitempty"`
	// Пользователь, который получил это достижение
	UserId string `json:"userId,omitempty"`
	// Дата в формате unix timestamp
	Date int64 `json:"date,omitempty"`
	// Вес достижения (нужно для календаря)
	Price int64 `json:"price,omitempty"`
	// Имя иконки для отображения в карточке
	IconName string `json:"iconName,omitempty"`

	IconColor string `json:"iconColor,omitempty"`

	Description string `json:"description,omitempty"`

	Title string `json:"title,omitempty"`
}
