/*
 * Fitness App
 *
 * This is a CRUD API for fitness app.
 *
 * API version: 1.0.0
 * Contact: soarex16@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package domain

type Course struct {
	Label string `json:"label,omitempty"`

	Description string `json:"description,omitempty"`

	Image string `json:"image,omitempty"`

	Exercises []Exercise `json:"exercises,omitempty"`

	Completed bool `json:"completed,omitempty"`
}
