/*
 * Fitness App
 *
 * This is a CRUD API for fitness app.
 *
 * API version: 1.0.0
 * Contact: soarex16@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package domain

type Exercise struct {
	Image string `json:"image,omitempty"`

	Title string `json:"title,omitempty"`

	Text string `json:"text,omitempty"`

	Completed bool `json:"completed,omitempty"`

	TimeToDo int64 `json:"timeToDo,omitempty"`

	Repeats int32 `json:"repeats,omitempty"`
}
