/*
 * Fitness App
 *
 * This is a CRUD API for fitness app.
 *
 * API version: 1.0.0
 * Contact: soarex16@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package domain

type User struct {
	Id string `json:"id,omitempty"`

	Username string `json:"username,omitempty"`

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`
}
